INSERT INTO CATEGORY(CATEGORY_ID) values('CATEGORYA');

INSERT INTO CATEGORY(CATEGORY_ID) values('CATEGORYB');

INSERT INTO CATEGORY(CATEGORY_ID) values('CATEGORYC');

INSERT INTO PRODUCTS(
PRODUCT_ID  ,	PRICE , 	PRODUCT_NAME  ,	CATEGORY_ID
) values('Pr01', 110.0,'XYZ_CATEGORYA','CATEGORYA');

INSERT INTO PRODUCTS(
PRODUCT_ID  ,	PRICE , 	PRODUCT_NAME  ,	CATEGORY_ID
) values('Pr02', 120.0,'PQA_CATEGORYB','CATEGORYB');

INSERT INTO PRODUCTS(
PRODUCT_ID  ,	PRICE , 	PRODUCT_NAME  ,	CATEGORY_ID
) values('Pr03', 130.0,'XYZ_CATEGORYC','CATEGORYC');